### PR TITLE
use preconditionsMet

### LINKED ISSUE #161: Consider approval in preconditionsMet

### PR DESCRIPTION
**Pull request by jessitron**
Fixes #161

this incorporates approval into preconditionsMet

and then uses it in all the places
which eliminates previousGoalSucceeded
which eliminates a circular import.

Also includes some bug fixes: await the promise of a boolean. Promises are always truthy

### CODE REVIEW

**Comment by jessitron** [comment]
OK I was kinda able to test tthis wiht hte dashboard, enough to determine htat there is a problem. I'm going to close the PR and reopen it later

**Comment by jessitron** [comment]
wrote a test, fixed one (pre-existing) problem

Now I can't testt because I can'tt upload tthe arttifact in a reasonable time.

**Comment by jessitron** [comment]
got a test in, no problems

**Comment by johnsonr** [comment]
Superseded

**Pull request closed without merging**
