### PR TITLE
Pre and post hooks

### PR DESCRIPTION
**Pull request by cdupuis**
this allows to execute arbitrary pre and post hooks in form of executables sitting inside `.atomist/hooks` of the repo. Scripts need to be named `<pre|post>-<environment>-<name>`.

if the hook exits with > 0 the goal will marked failed.

Example hook script at https://github.com/cdupuis/cd2/blob/master/.atomist/hooks/post-code-react

### CODE REVIEW

**Comment by jessitron** [comment]
You sure you don’t want to use yaml?

... kidding!

**Comment by jessitron** [comment]
I have some actual useful feedback on this but my computer is installing updates. Will submit comments in the format of a commit in a few hours

**Comment by cdupuis** [comment]
> I have some actual useful feedback on this but my computer is installing updates. Will submit comments in the format of a commit in a few hours

That's the best form of feedback.

Piece of background here: I was contemplating to use `.js` as hooks and then just run `node <hook>.js` instead of `bash <hook>.sh`. Maybe that would be more aligned with what we want?  I'm torn as with `sh` files you can wrap other stuff you might have lying around easily. 

I'm really interested to hear what people think about the usefulness of the general concept.

**Comment by ddgenome** [comment]
Why not support anything the OS can run that is executable and of the form `<environment>-<name>_<pre|post>-hook`?

**Comment by cdupuis** [comment]
Yeah, that would certainly work too. I didn't optimise this for greatest flexibility in terms of what can be run. I really just wanted to see if we feel something like this is useful at all.

**Comment by cdupuis** [comment]
I changed it to what @ddgenome suggested (also updated the description of PR to reflect this).

**Comment by johnsonr** [comment]
Will consider as #320

**Pull request closed without merging**
